Signature port
gbMichelle/Vulpes pull request #64
Opened 2019-12-24 03:01 UTC by gbMichelle

Closes #62 
Closes #47 

Needs #63 addressed before this can be dealt with. I still want to rename LiteSignature to CodeSignature for clarity.

2020-01-25 05:18 UTC, Mimickal requested changes
Sorry this took so long

2020-01-25 05:18 UTC, Mimickal commented on vulpes/memory/global.cpp
>          name_pointer = &ui_name[0];
Just writing `ui_name` without any brackets or symbols should achieve this same effect. Alternately, defining it as `static const char ui_name* = "ui";` should (re: may) work.

2020-01-25 05:18 UTC, Mimickal commented on hooker/hooker.hpp
> +    }
I'm not normally a stickler for style, but having an arbitrary number of parameters and operations per line here makes things harder to follow. Remember one concept per line, and vertical space is free.

2020-01-25 05:18 UTC, Mimickal commented on vulpes/fixes/host_refusal.cpp
> +static Patch(host_refusal_fix2, NULL, {0xEB});
You have constants defined for these `{0xEB}` style values, but not here.

2020-01-25 05:18 UTC, Mimickal commented on vulpes/fixes/shdr_trans_zfighting.cpp
> +         && patch_shader_trans_zfighting3d_fix.build(sig_addr3 + 0x34 + 0x50)) {
You know what I'm going to say about these constants.

2020-01-25 05:18 UTC, Mimickal commented on vulpes/hooks/console.cpp
> +    console_hook__return_to_halo_con_in = addr + 23;
23 is a magic number

2020-01-25 05:18 UTC, Mimickal commented on vulpes/upgrades/map.cpp
> +                patch_get_map_crc.address()+2);
Are 2 and 13 magic numbers?

2020-01-25 05:18 UTC, Mimickal commented on vulpes/vulpes.cpp
> +        signature_text_segment_data.search(0x400000, 0x401000));
What are these values?

2020-01-25 05:34 UTC, gbMichelle commented on vulpes/memory/global.cpp
>          name_pointer = &ui_name[0];
This would get me an ISO C++ warning/error

2020-02-07 03:03 UTC, Mimickal approved these changes

2020-02-07 06:26 UTC, merged