Clean up build.pl and add new build_type
gbMichelle/Vulpes pull request #67
Opened 2019-12-30 01:51 UTC by gbMichelle

The new chimera replaces the strings.dll and disables dll loading from controls/. It does load mods from a mods/ folder though. This new build type installs the loader there.

No doubt will this cause issues down the line with people installing the mod.

2019-12-31 10:47 UTC, Mimickal requested changes
Why are we forcibly loading build configuration from a YAML file? I could see it being an option for this build script, but the script itself should be the thing taking in arguments for build types and output locations.

2019-12-31 10:47 UTC, Mimickal commented on build.pl
> +        print "Invalid build_type";
Should print what the invalid build type is, also possibly with a list of valid build types.

2019-12-31 14:14 UTC, gbMichelle commented
Honestly. I wasn't really sure of the value of being able to give these as arguments. And I hadn't really figured out how I want to do that.

I could add this as an extension of #55

2020-01-25 03:56 UTC, Mimickal approved these changes

2020-01-25 05:36 UTC, merged